services:
    bitbag_sylius_adyen_plugin.controller.notify:
        class: BitBag\SyliusAdyenPlugin\Controller\NotifyController
        public: true
        arguments:
            - "@payum"
            - "@sylius.repository.payment"
