services:
    bitbag_sylius_adyen_plugin.payment_processing.refund:
        public: true
        class: BitBag\SyliusAdyenPlugin\PaymentProcessing\RefundPaymentProcessor
        arguments:
            - "@payum"
            - "@session"